spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.210.219:3306/english?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: hzy
    password: 123456
  devtools:
    restart:
      # 热部署开关
      enabled: true
myenglish:
  name: HappyEnglish
  profile: C:\Users\14172\AppData\Local
  copyrightYear: 2021
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

server:
  port: 8107

